//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewHistory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public System.DateTime TransactionDate { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual TransactionDetail TransactionDetail { get; set; }
    }
}
